### ISSUE TITLE
Probability of choosing old snapshot is zero with RCModelSelector

### ISSUE THREAD

**Issue by clement-wespiser** [bio-phys/aimmd#11] opened 2024-04-12 15:57 UTC
Hi,

I'm trying to reproduce the results of the [toy system notebook](https://github.com/bio-phys/aimmd/blob/main/examples/1_Toy_pytorch_simple_setup.ipynb). 

When running the TPS simulation, I get a `ZeroDivisionError` thrown by the `ShootingPointSelector.probability_ratio` function because `p_old==0`. Depending on the _distribution_ and _scale_ parameters used to instantiate the `RCModelSelector`, this happens after ~10 to ~800 steps. The [full report](https://github.com/bio-phys/aimmd/files/14960654/bug_report.txt) is attached.

Any idea of why this happens? Everything runs smoothly when one of the built-in OPS selector is used. 

Thanks

**Comment by hejung** [comment] 2024-04-12 16:39
Hi,

thanks for the report! From a first glance I am not sure what is happening there, because an old shooting point with `p_old=0` should not be possible to be selected as a shooting point. I will try to have a detailed look at it during the weekend.

Does this also happen when you use `scale=1` and `distribution="lorentzian"`, i.e. the defaults? And could you share the `scale` and `distribution` that result in the earliest crash (that will make it easier for me to reproduce).

**Comment by clement-wespiser** [comment] 2024-04-12 21:00
Hi,

Thanks for the quick reply.
It happened with default values, I also tried`scale=0.1, 1, 10` with both `lorentzian` and `gaussian` distributions

**Comment by hejung** [comment] 2024-04-15 12:16
This should be fixed on #13 . I have not merged it yet because I still need to test/make sure that it does not break the distributed TPS. I should be able to test this in the coming days and am confident that this fix will not break the distributed TPS, so most likely this will be merged soon.

Thanks again for reporting!

**Closed** 2024-05-07 20:49 UTC
